# Generated by Django 5.0.7 on 2025-08-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
