# Generated by Django 5.0.7 on 2025-08-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_breakfastvoucher_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastvoucher',
            name='voucher_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
