# Generated by Django 5.0.7 on 2025-08-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_breakfastvoucher_voucher_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfastvoucher',
            name='voucher_date',
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='qr_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='breakfastvoucher',
            name='qty',
            field=models.IntegerField(),
        ),
    ]
