# Generated by Django 5.0.7 on 2025-08-28 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_breakfastvoucher_voucher_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastvoucher',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='breakfastvoucher',
            name='kids',
            field=models.IntegerField(default=0),
        ),
    ]
