# Generated by Django 5.0.7 on 2025-08-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_breakfastvoucher_adults_breakfastvoucher_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfastvoucher',
            name='qr_code_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
