# Generated by Django 5.0.7 on 2025-09-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_users_is_active_users_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
