# Generated by Django 5.0.7 on 2025-09-01 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_usergroup_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(to='app1.users'),
        ),
    ]
