# Generated by Django 5.0.7 on 2025-09-01 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_alter_usergroup_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergroup',
            name='group_name',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='users',
            field=models.ManyToManyField(blank=True, to='app1.users'),
        ),
    ]
