# Generated by Django 5.0.7 on 2025-09-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_usergroup_group_name_alter_usergroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
