# Generated by Django 5.0.7 on 2025-09-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_usergroup_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='group_name',
            new_name='name',
        ),
    ]
