# Generated by Django 5.0.7 on 2025-09-02 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_rename_group_name_usergroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.location'),
        ),
    ]
