# Generated by Django 5.0.7 on 2025-09-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_checklist_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='location',
        ),
        migrations.AddField(
            model_name='checklist',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='checklists', to='app1.location'),
        ),
    ]
