# Generated by Django 5.0.7 on 2025-09-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_remove_checklist_location_checklist_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='locations',
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(db_column='checklist_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app1.checklist'),
        ),
    ]
