# Generated by Django 5.0.7 on 2025-09-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_remove_checklist_locations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(db_column='checklist_id', on_delete=django.db.models.deletion.CASCADE, to='app1.checklist'),
        ),
    ]
