# Generated by Django 5.0.7 on 2025-09-02 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_alter_checklistitem_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.checklist'),
        ),
    ]
