# Generated by Django 5.0.7 on 2025-09-02 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_checklistitem_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='app1.location'),
        ),
    ]
