# Generated by Django 5.0.7 on 2025-09-02 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_checklist_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, db_column='location_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklists', to='app1.location'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(db_column='checklist_id', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app1.checklist'),
        ),
    ]
