# Generated by Django 5.0.7 on 2025-09-02 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_alter_checklist_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.location'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='checklist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app1.checklist'),
        ),
    ]
