# Generated by Django 5.0.7 on 2025-09-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_voucher_check_in_date_voucher_check_out_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='room_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='voucher',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='kids',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='qr_sent_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voucher',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='room_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
